version: "3.9"

services:
  keycloak-carapp:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloack/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    networks:
      app-network:
        ipv4_address: 192.168.15.2

  spring2:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
    networks:
      app-network:
        ipv4_address: 192.168.15.3
    volumes:
      - ./docker/keycloack/spring-app/application.properties:/app/application.properties

#  react:
##    build: ./remote_car_frontend
#    build: ./exampleWebSocketWebApp
#    ports:
#      - "3000:80"
#    networks:
#      app-network:
#        ipv4_address: 192.168.15.5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
#      - react
      - spring2
      - keycloak-carapp
    networks:
      app-network:
        ipv4_address: 192.168.15.4

networks:
  app-network:
    driver: bridge
    name: app-network
    ipam:
      config:
        - subnet: 192.168.15.0/24