version: "3.9"

services:
  keycloak-carapp:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloack/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    networks:
      - app-network
  spring:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
    networks:
      - app-network

#  react:
#    build: ./frontend
#    ports:
#      - "3000:80"
#    networks:
#      - app-network
#
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - spring
#      - react
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
